auth_token = "poop"
log_level = "debug"

data_path = "/tmp/bldr-worker/data"
log_path = "/tmp/bldr-worker/log"

recreate_ns_dir = true
network_interface = "eth0"
network_gateway = "192.168.211.2"


[github]
client_id = "GITHUB_CLIENT_ID"
client_secret = "GITHUB_CLIENT_SECRET"
